name: ahmad_tuflihun_mobile_dev_test_fast_eight
description: "Developer Test Ahmad Tuflihun"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  # Core
  flutter_bloc: ^8.1.4
  flutter_native_splash: ^2.3.10
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  workmanager: ^0.5.2
  get_it: ^8.0.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  image_picker: ^1.1.2

  # Utils
  flutter_gen: ^5.4.0
  flutter_dotenv: ^5.0.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  local_auth: ^2.2.0
  flutter_screenutil: ^5.9.0
  device_preview: ^1.2.0
  permission_handler: ^11.3.0
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.1.2
  flutter_downloader: ^1.11.7
  open_file_plus: ^3.4.1
  tap_debouncer: ^2.2.0
  talker_dio_logger: ^4.1.5
  url_launcher: ^6.2.6

  # Network
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  dio_cookie_manager: ^3.1.1
  cached_network_image: ^3.3.1
  http_parser: ^4.0.2

  # Design
  text_scroll: ^0.2.0
  flutter_form_builder: ^9.2.1
  flutter_svg: ^2.0.10+1
  pull_to_refresh: ^2.0.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  video_player: ^2.9.1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svgs/
    - assets/fonts/montserrat/
    - assets/fonts/poppins/
